apiVersion: v1
kind: Namespace
metadata:
  name: monarch-tests
---
apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: l4-gpu-4x
spec:
  priorities:
  - machineType: g2-standard-48
    gpu:
     count: 4
     type: nvidia-l4
  nodePoolAutoCreation:
    enabled: true
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ResourceFlavor
metadata:
  name: "default-flavor"
spec:
  nodeLabels:
    cloud.google.com/compute-class: l4-gpu-4x
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: "cluster-queue"
spec:
  namespaceSelector: {}
  resourceGroups:
  - coveredResources: ["cpu", "memory", "nvidia.com/gpu", "ephemeral-storage"]
    flavors:
    - name: "default-flavor"
      resources:
      - name: "cpu"
        nominalQuota: 100
      - name: "memory"
        nominalQuota: 500Gi
      - name: "nvidia.com/gpu"
        nominalQuota: 8
      - name: "ephemeral-storage"
        nominalQuota: 1Ti
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  namespace: "monarch-tests"
  name: "user-queue"
spec:
  clusterQueue: "cluster-queue"
